### ISSUE TITLE
When `relativePath: true`, even absolute paths are for icons in sidebar are resolved as relative.

### ISSUE THREAD

**Issue by filipgoc** [docsifyjs/docsify#877] opened 2019-07-04 20:52 UTC
## Bug Report
When `relativePath: true`, absolute paths are for icons in sidebar are resolved as relative.

#### Steps to reproduce

Set `relativePath: true`

```
└── docs
    ├── _sidebar.md
    ├── guide.md
    └── subfolder
        ├── _sidebar.md
        ├── guide.md
```

In the both  _sidebar files, I have `- [![](/assets/home.svg)Home](/ "Home")`

#### What is current behaviour

While the link gets resolved as absolute (👍 ), 
for images, 
the data-origin is correct (👍 ), but the img scr is _relative_ and thus failing (👎 )

```html
<a href="#/" title="Home"><img src="/subfolder/assets/home.svg" data-origin="/assets/home.svg" alt="">Home</a>
```

#### What is the expected behaviour

The img src should be absolute: 
"/assets/home.svg"

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version:  4.9.4
- Docsify plugins: pagination, themeable

**Comment by tiptronic** [comment] 2019-07-24 15:29
While I understand your intention (and you're right), here's a small note:
But both of the mentioned paths are absolute paths:
- /subfolder/assets/home.svg
- /assets/home.svg

they simple start at a different root-directory. A relative path would ideally start with an './' (or even without a slash).

This is an important feature, because otherwise it's cumbersome to link from one .md to the contents of another <sibling/parent/child>.md.

**Comment by timaschew** [comment] 2019-11-22 21:07
Resolving image seems to use a different algorithm that's why images are not working.

**Comment by jcayzac** [comment] 2020-12-10 01:05
I can reproduce this in any page:

```md
![Secure website image](/_assets/secure-website.png)
```

is resolved as:

- `{base-path}#/_assets/secure-website.png` when i'm e.g. at `#/quickstart`, but as
- `{base-path}#/ja/_assets/secure-website.png`, which doesn't exists and returns 404, when i'm e.g. at `#/ja/quickstart`.

Given the URL is absolute I don't understand why Docsify feels like it should consider it relative, **especially since I don't set `relativePath`**.

**Comment by jhildenbiddle** [comment] 2024-03-02 04:17
Bug acknowledged. Tracking with #1891.

**Closed by jhildenbiddle** 2024-03-02 04:17 UTC
Labels: bug, help wanted, path-resolving, PR Welcome
