### ISSUE TITLE
open url is blank

### ISSUE THREAD

**Issue by ajaxsync** [docsifyjs/docsify#1800] opened 2022-05-16 14:53 UTC
The GitHub pages built by docsify opened normally in the afternoon. I just opened it and found that it was all blank. I tried to open it in a different browser from the PC and the mobile phone, but it was all blank. Opening the official website has always been in the loading state, what is going on?

![image](https://user-images.githubusercontent.com/52560448/168621543-1c833a12-6ed8-441a-802f-b8851711e8d9.png)

**Comment by ajaxsync** [comment] 2022-05-16 15:10
files failed to load. I thought that there might be a problem with the CDN. Please check, thank you

![image](https://user-images.githubusercontent.com/52560448/168624568-32070509-0d8b-4739-b6a6-5b8d830d894a.png)

![image](https://user-images.githubusercontent.com/52560448/168624720-87d40213-370a-4f20-8ec6-fc89157c8a57.png)

**Comment by ajaxsync** [comment] 2022-05-16 15:13
![image](https://user-images.githubusercontent.com/52560448/168625735-e60f77da-4aca-4786-bd40-4fc7d21a3065.png)

**Comment by tyntl** [comment] 2022-05-16 17:13
I had changed the configuration in the index.html and resolve some basic function of my note blog, and it works again.
u can see some href from https://www.bootcdn.cn/docsify/ to replace some href of original configuration.
sorry for my pool English and hope to help u.

**Comment by sy-records** [comment] 2022-05-16 23:19
Duplicate of #1795

**Closed by sy-records** 2022-05-16 23:19 UTC

**Comment by ajaxsync** [comment] 2022-05-17 04:14
> I had changed the configuration in the index.html and resolve some basic function of my note blog, and it works again. u can see some href from https://www.bootcdn.cn/docsify/ to replace some href of original configuration. sorry for my pool English and hope to help u.

Thank you very much, I tried to replace the bootcdn and it works
