### ISSUE TITLE
Scroll magnet doesn't work when accessing the documentation from a link with an anchor

### ISSUE THREAD

**Issue by dokydok** [docsifyjs/docsify#908] opened 2019-08-18 07:37 UTC
## Bug Report
The scroll magnet in the navbar doesn't respond when accessing the documentation from a link with "?id=" param

#### Steps to reproduce
Go to [https://docsify.js.org/#/configuration?id=homepage](https://docsify.js.org/#/configuration?id=homepage)
Notice that the homepage section is selected in the navbar, scroll up and down, the selection doesn't change.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version: 
- Docsify plugins:

**Comment by yuxesd** [comment] 2019-11-04 14:01
I also encountered the same problem

**Comment by anikethsaha** [comment] 2019-11-21 13:35
it is supposed to be like that cause of the `id` parameter you queried in the header. 

try this https://docsify.js.org/#/configuration and scroll.

Closing this as its intended behavior. 
Please open a new issue if you think this doesn't solve your issue 

thanks 👍

**Closed by anikethsaha** 2019-11-21 13:35 UTC
