### ISSUE TITLE
Question: Parsing URL Links that have characters wrapped in colons (ie :w:)

### ISSUE THREAD

**Issue by andrefox333** [docsifyjs/docsify#1839] opened 2022-07-18 19:08 UTC
Hi team, quick question on how to properly manage URL links that has `:v:` or any character that is wrapped in a colon. Right now it's trying to convert these `:v:` into emoji characters... Any help is deeply appreciated. Thanks!

**Comment by jhildenbiddle** [comment] 2022-07-30 02:13
Duplicate of #1823

**Closed** 2022-08-03 03:52 UTC
Labels: duplicate
