### ISSUE TITLE
Hide the navbar

### ISSUE THREAD

**Issue by oren** [docsifyjs/docsify#872] opened 2019-07-02 07:14 UTC
#### What problem does this feature solve?
Some sub sections of my website don't need navbar at all. I created a new project with the init command and all I have is this:
```
    window.$docsify = {
      name: '',
      repo: ''
```
but the navbar is showing. I don't need navbar for every section of my website.

#### What does the proposed API look like?
I don't know. This might be a bug or I just don't know how to use the existing API

#### How should this be implemented in your opinion?
Not sure

#### Are you willing to work on this yourself?
Depends on the complexity

**Comment by oren** [comment] 2019-07-04 02:06
I think currently the sidebar is always visible. I assume that based on this line:
https://github.com/docsifyjs/docsify/blob/develop/src/core/render/tpl.js#L49

**Comment by oren** [comment] 2019-07-04 18:11
I worked around it by hiding and showing the icon based on the location.hash. Dirty but works:
```js
      window.addEventListener('hashchange', hashHandler, false);

      function hashHandler() {
        if(location.hash.startsWith("#/surf/")) {
          document.getElementsByClassName("sidebar-toggle-button")[0].style.display = "block";
        } else {
          document.getElementsByClassName("sidebar-toggle-button")[0].style.display = "none";
        }
      }
```

**Comment by anikethsaha** [comment] 2019-11-24 09:12
did you try this  ` loadNavbar: false` ?

**Comment by methodbox** [comment] 2019-12-31 17:32
> did you try this ` loadNavbar: false` ?

You know none of these flags actually work?

**Comment by anikethsaha** [comment] 2019-12-31 18:13
> > did you try this ` loadNavbar: false` ?
> 
> You know none of these flags actually work?

I didnt get you

**Comment by anikethsaha** [comment] 2019-12-31 18:15
By default both `sidebar` and `navbar` are false which means, they are not visible.

**Comment by methodbox** [comment] 2019-12-31 20:30
> By default both `sidebar` and `navbar` are false which means, they are not visible.

Then why is there a side nav shown by default, and why doesn’t `sideBar: “mysidebar.md” do anything?

Setting `sidebar: “false”` doesn’t hide it, either, and since it won’t load mine, it’s useless.

It looks like `navBar: “mynavbar.md”` works, but since I can’t get rid of (and it doesn’t do so automatically, which seems it should) the side bar, they overlap.

**Comment by anikethsaha** [comment] 2019-12-31 20:40
Thanks for the details 👍 
I will try to reproduce it locally. 

It seems like a bug here
https://github.com/docsifyjs/docsify/blob/db97a1d22a89ddb8de0e1dcbb290a7d7ca4ec1f5/src/core/render/index.js#L50

**Comment by trusktr** [comment] 2020-01-01 00:00
> Then why is there a side nav shown by default, and why doesn’t sideBar: “mysidebar.md”do anything?

There might be bugs that we should fix. We're in the process of adding unit tests, so hopefully any regressions won't happen in the future. We're not the original authors, so we're not 100% aware of any regressions, if any, but if you see anything, please do open an issue. That'd help a lot!

**Comment by trusktr** [comment] 2020-01-01 00:03
Here's an idea for a workaround: you could add a CSS style that applies `display: none` on certain pages for the navbar, and on other pages make sure to remove that CSS style.

Another idea: you could listen to route changes, and add/remove the CSS style on route changes.

**Comment by methodbox** [comment] 2020-01-01 17:11
Yep, totally understand how I can work around it, but then, if I’m going to take the time to build custom logic or CSS for and “auto”-generated site, then it isn’t very auto, is it?

The goal of a tool like this seems like it should be to be fairly effortless and definitely shouldn’t require writing additional code, otherwise I could just use JSDoc out of the box and do the custom theme work myself.

**Comment by anikethsaha** [comment] 2020-01-01 17:57
We are sorry for this issue.
I will find a time soon to fix this one.

This project was not active for a long time and we are finding time in between to resolves these types of issues. we don't have tests to support us either.  having tests would pick these kinds of bugs.
We think too that we should not have workarounds to get our stuff going but at this point, this is the quick fix. 

If you find the fix then feel free to submit a PR to help others 👍

**Comment by methodbox** [comment] 2020-01-01 18:43
> We are sorry for this issue.
> I will find a time soon to fix this one.
> 
> This project was not active for a long time and we are finding time in between to resolves these types of issues. we don't have tests to support us either. having tests would pick these kinds of bugs.
> We think too that we should not have workarounds to get our stuff going but at this point, this is the quick fix.
> 
> If you find the fix then feel free to submit a PR to help others 👍

Will do. I might take a look tomorrow.

**Comment by anikethsaha** [comment] 2020-01-01 18:48
> Will do. I might take a look tomorrow.

Cool

**Comment by anikethsaha** [comment] 2020-02-14 08:23
After looking at it. 
`loadNavBar` options is working fine as expected. Please check whether you have `<nav>` tag in your HTML markup or not !!

### `loadSideBar` and `loadNavBar` set to `false`

When they are set to `false, they don't read for `_sidebar.md` and `_navBar.md` file and don't render their content. 
**But**, `sidebar` still gets render because of the `heading` tags present in your `homepage` MD file (`Default: README.md`), 
both the config are doing their purpose of rendering  `_sidebar.md` and `_navBar.md`. 

Perhaps, if you want to hide the sidebar, we can introduce an options `hideSideBar` to fix it.

**Comment by anikethsaha** [comment] 2020-02-14 08:33
> Here's an idea for a workaround: you could add a CSS style that applies `display: none` on certain pages for the navbar, and on other pages make sure to remove that CSS style.

We can totally do this and release a new plugin with the `hideSidebar` option provided by the plugin. But one thing about supporting it directly from the core is that it will be performance-friendly if we support this through core. 

**cause** simply hiding the sidebar will fix the problem but docsify will still do all the steps of rendering, so if we are hiding it anyway, why wasting time in rendering it in first place. !!!!!


Should we go for plugin or support from the core?

cc @docsifyjs/core @trusktr @jthegedus @Koooooo-7

**Comment by anikethsaha** [comment] 2020-02-14 09:05
Check the implementation from the core.

https://github.com/anikethsaha/docsify/commit/9b218a145ec1ae88e20563425f17ef7af57e5ae1#diff-250dfe7435d59fa33e80765c47190dd5R95

**Comment by Koooooo-7** [comment] 2020-02-14 11:30
@anikethsaha  
tbh, Idk how many situations that we need to hide the sidebar(and hide the search plugins), 
it seems like a static pages web. :sweat_smile: : 
About the `hideSidebar`,I think it can be merged to `loadSidebar = false`.cuz I think current `loadSidebar=false` is useless. 
Although I think this configuration(hide sidebar) is not so necessary now ,If we hv more configurations to satisfy different needs,  it is better.

**Comment by anikethsaha** [comment] 2020-02-14 12:09
> About the hideSidebar,I think it can be merged to loadSidebar = false.cuz I think current loadSidebar=false is useless.

by default, we use `loadSidebar = false` so docsify won't show sidebar by default if we change it to this.

I would have preferred the plugin cause this are user's preference choices and core should not be changed for every little enhancement but due to perf factors, i am leaning more towards adding it to the core.

**Comment by Koooooo-7** [comment] 2020-02-14 13:48
>I would have preferred the plugin cause this are user's preference choices and core should not be changed for every little enhancement but due to perf factors
yep, u r right.

**Comment by anikethsaha** [comment] 2020-02-14 14:51
> , I wish there would hv a better way instead of setting the styling back.😂

Yep,,,,I see that too...you have better option?  

Also, I am going with implementing that in the core !!

**Comment by anikethsaha** [comment] 2020-02-14 14:53
@Koooooo-7 do you want to take this in a better way? else I will go with my implementation !!

or you want to continue as a follow-up of the  anikethsaha@9b218a1 solution

**Comment by Koooooo-7** [comment] 2020-02-14 15:04
@anikethsaha  I dont find a better way right now.:joy:
Although, I found that perhaps we can change the [tpl.js] (https://github.com/docsifyjs/docsify/blob/develop/src/core/render/tpl.js).
```js
  return (
    (isMobile ? `${aside}<main>` : `<main>${aside}`) +
    '<section class="content">' +
    '<article class="markdown-section" id="main"><!--main--></article>' +
    '</section>' +
    '</main>'
  )
```
I dont think it is a good way either...I haven't found when the stylings were setted yet.
I think u can make ur implementation at now, if  someone finds a good  way , he may update it then.:dog:

**Comment by anikethsaha** [comment] 2020-02-14 15:08
> @anikethsaha I dont find a better way right now.😂
> Although, I found that perhaps we can change the [tpl.js](https://github.com/docsifyjs/docsify/blob/develop/src/core/render/tpl.js).
> 
> ```js
>   return (
>     (isMobile ? `${aside}<main>` : `<main>${aside}`) +
>     '<section class="content">' +
>     '<article class="markdown-section" id="main"></article>' +
>     '</section>' +
>     '</main>'
>   )
> ```
> 

I think this approach needs either new class name or again need to do the same styling here !!!

**Comment by Koooooo-7** [comment] 2020-02-14 15:18
@anikethsaha  yep, I prefer to ur implementation.

**Comment by methodbox** [comment] 2020-02-14 21:38
> > About the hideSidebar,I think it can be merged to loadSidebar = false.cuz I think current loadSidebar=false is useless.
> 
> by default, we use `loadSidebar = false` so docsify won't show sidebar by default if we change it to this.
> 
> I would have preferred the plugin cause this are user's preference choices and core should not be changed for every little enhancement but due to perf factors, i am leaning more towards adding it to the core.

I think this might be the part everyone is missing in this thread: `loadSideBar` set to `false` doesn’t actually work.

If the purpose of this flag is to show/not show the sidebar why would you create another key to hide the sidebar? And if it’s set to `false` to begin with, why does it still show anyway?

It seems like this should be a proper `boolean` which explicitly shows/hides the sidebar.

It should be as simple as conditionally rendering the component like:

```js
function SideBar(props) {
  return (
    <>
      {props.showSideBar ?
        <div>
          ...sidebar content
        </div>
      : null}
    </>
  )
}
```

**Comment by Koooooo-7** [comment] 2020-02-15 04:41
> I think this might be the part everyone is missing in this thread: `loadSideBar` set to `false` doesn’t actually work.

Currently, when u set `loadSidebar = false`,it would render that the left part is the search box and the titles(and subtitles) of  content instead the sidebar. 
Personally, I think it is useless.but  if someone needs this, it would be useful.

> If the purpose of this flag is to show/not show the sidebar why would you create another key to hide the sidebar? And if it’s set to `false` to begin with, why does it still show anyway?

When  `LoadSidebar = false`, it will render as I said above.
When `HideSidebar = false`, it will render that the content only, no search box , no titles.
Those configurations seems a little confused, maybe we need change to another names and distinguish them in another way.

**Comment by anikethsaha** [comment] 2020-02-15 07:25
as I said `loadSidebar` is not meant to hide/display the whole sidebar.
we need a separate option for that so we are going with `hideSidebar` for now !!

**Closed** 2020-02-20 16:49 UTC
Labels: bug
