### ISSUE TITLE
After [filename](README.md ':include'), the docsify-tabs plugin in README.md fails

### ISSUE THREAD

**Issue by zhangkaiqiu** [docsifyjs/docsify#2000] opened 2023-03-03 07:22 UTC
#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version:   <script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
- Docsify plugins: docsify-tabs v1.6.0

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by zhangkaiqiu** [comment] 2023-03-03 07:51
<iframe src="https://codesandbox.io/embed/trusting-engelbart-z6k1zv?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="trusting-engelbart-z6k1zv"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by Koooooo-7** [comment] 2023-03-07 11:32
Hi @zhangkaiqiu , could plz provide more details about it? I checked the sandbox above. it does show the tabs.

**Comment by zhangkaiqiu** [comment] 2023-03-07 13:35
I'm sorry I didn't describe clearly.

When I use the docsify-tab plugin normally, I expect the display to be as follows:
![image](https://user-images.githubusercontent.com/35255656/223436391-ad21cdb6-2083-499b-bf90-08673a6a0ff0.png)
It is like the display effect of google browser tabs.

Its source code is as follows:
```
<!-- tabs:start -->

#### **English**

Hello!

#### **French**

Bonjour!

#### **Italian**

Ciao!

<!-- tabs:end -->
```
![image](https://user-images.githubusercontent.com/35255656/223437026-cb828d01-fb29-48d5-a9d2-92c9dadaa68d.png)

But when I apply it with include: 
![image](https://user-images.githubusercontent.com/35255656/223437217-b42b8eca-3bc4-4922-8485-544d7010743a.png)
Its display effect is as follows:

**Comment by zhangkaiqiu** [comment] 2023-03-07 13:41
https://codesandbox.io/embed/eloquent-maxwell-oepc7x?fontsize=14&hidenavigation=1&theme=dark

**Comment by Koooooo-7** [comment] 2023-03-09 07:51
I see, you wanna use `:include` to get a tab from other md resource.
I m not quite sure whether `docsify-tab` supports it or not.

Hi @jhildenbiddle , could  plz you take a look on this?

**Comment by jhildenbiddle** [comment] 2024-02-15 23:12
Plugins like docsify-tabs are unable to process [embedded](https://docsify.js.org/#/embed-files?id=embed-files) markdown content because docsify does not send embedded markdown through the plugin chain. Instead, docsify transforms markdown into HTML and makes that HTML available to plugins only within the `afterEach` [hook](https://docsify.js.org/#/write-a-plugin).

**Comment by jhildenbiddle** [comment] 2024-02-15 23:13
Marking as duplicate of more appropriately named issue: #2373

**Closed by jhildenbiddle** 2024-02-15 23:13 UTC
Labels: enhancement
