### ISSUE TITLE
Translation image does not load properly

### ISSUE THREAD

**Issue by louislivi** [docsifyjs/docsify#773] opened 2019-02-16 05:59 UTC
![image](https://user-images.githubusercontent.com/23403807/52895285-07409e00-31f3-11e9-9c94-34156b4d0ee8.png)

**Comment by louislivi** [comment] 2019-02-18 00:53
#774

**Comment by timaschew** [comment] 2019-02-18 12:04
dupe of https://github.com/docsifyjs/docsify/issues/768

**Closed by timaschew** 2019-02-18 12:04 UTC
