### ISSUE TITLE
使用全文搜索时中文标题未解码Chinese title not decoded when using full text search

### ISSUE THREAD

**Issue by Tajang-ctf** [docsifyjs/docsify#1790] opened 2022-04-20 08:22 UTC
使用全文搜索时中文标题未解码
Chinese title not decoded when using full text search
我的全文搜索插件如下
![image](https://user-images.githubusercontent.com/63721558/164183755-002ee5eb-4f42-441c-96f9-986fe690b73e.png)
开启本地docsify服务时，搜索页面如下
![image](https://user-images.githubusercontent.com/63721558/164183875-f9e1ea0b-fb07-4606-9f70-b95288c36fae.png)
搜索出来的中文标题未解码
我看到有一个方法说，修改src/plugins/component.js的内容，可是我是Windows本地运行，并且是引入的远程插件，并没有这些文件，请问我该如何解决？

**Comment by sy-records** [comment] 2022-04-20 09:32
duplicate of #1769

I cannot reproduce your question, please follow the issue template for your question.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/33931153/164197646-536e6626-e4bc-4360-a81e-c94aaa7ee3d8.png">

**Closed by sy-records** 2022-04-20 09:32 UTC

**Comment by Tajang-ctf** [comment] 2022-04-20 09:37
The src/plugins/component.js file is not referenced in my environment
i use 
```
<script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>
```

**Comment by Tajang-ctf** [comment] 2022-04-20 09:49
I have downloaded this file locally and quoted, but my Chinese title is still not decoded. Do you need to modify this search.min.js
in what part?

**Comment by sy-records** [comment] 2022-04-20 10:17
I don't know what you modified. You should tell me how to reproduce this problem, follow the issue template, and provide a sandbox or repo.

**Comment by Tajang-ctf** [comment] 2022-04-20 10:27
Here is my docsify: https://wiki.ctfking.com/
You can try the search function, search for Lxxx
The Chinese title of the displayed page is undecoded

**Comment by Tajang-ctf** [comment] 2022-04-20 10:27
如果有需要，我可以将我的docsify本地环境上传到github仓库

**Comment by Tajang-ctf** [comment] 2022-04-20 10:28
I can upload my docsify local environment to the github repo if needed

**Comment by sy-records** [comment] 2022-04-20 23:29
Your file path should be in English.

```markdown
- 首页

  - [介绍](/)
- 个人知识库

  - [Web安全](个人知识库/Web安全/)
    - [SQL注入](/个人知识库/Web安全/SQL注入.md)
  - [代码审计](个人知识库/代码审计/)
    - [PHP代码审计](个人知识库/代码审计/PHP代码审计.md)
    - [Java代码审计](个人知识库/代码审计/Java代码审计.md)
- 更新日志
  - [更新日志](更新日志/README.md)
```

**Comment by Tajang-ctf** [comment] 2022-04-21 01:33
Why can he?
https://i.xiinnn.com/#/

**Comment by Tajang-ctf** [comment] 2022-04-21 13:46
你好，很道歉打扰你多次，这次我找到了原因，我这里全文搜索功能出现未解码显示是因为本地Chrome浏览器的原因。在我重置浏览器设置之后，便可正确显示中文标题。但我尚且不知Chrome的哪些设置导致了中文标题乱码，已排除扩展程序的原因。


Hello, I apologize for bothering you many times. This time I found the reason. The undecoded display of the full-text search function here is because of the local Chrome browser. After I reset my browser settings, the Chinese title is displayed correctly. But I still don't know which settings in Chrome caused the Chinese title to be garbled, and the extension has been ruled out.
