### ISSUE TITLE
Sidebar logo occasionally glitches

### ISSUE THREAD

**Issue by Zaeems** [docsifyjs/docsify#1796] opened 2022-05-04 10:22 UTC
#### Steps to reproduce

1. Add to $window.docsify: `logo: "https://raw.githubusercontent.com/Zaeems/iMS-User-Scripts/main/iMS_Dark_Mode.svg",` and `coverpage: true,`
2. Add to custom.css: `.app-name-link img { height: 3rem; }`
3. Ensure _coverpage.md exists and contains something, example: `<!-- _coverpage.md --> Test`
4. Serve the site, then scroll below the coverpage

#### What is current behaviour

Occasionally, the sidebar logo will move really quicky for less than a second.

https://user-images.githubusercontent.com/46079004/166661243-0510ffdb-de32-49bc-ba65-f5f4eae49f5b.mp4

#### What is the expected behaviour

Sidebar logo to remain in place.

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10 64-bit
- Node.js version: v16.14.1
- npm/yarn version: 8.5.0
- Browser version: Opera GX LVL3 (core: 85.0.4341.72)
- Docsify version: 4.12.2
- Docsify plugins: zoom-image, search, darklight-theme

#### Please create a reproducible sandbox 

I can't get the sandbox to work. 

https://zaeems.github.io/#/

**Comment by Zaeems** [comment] 2022-05-04 11:50
To reproduce - pause the scrollwheel at this point for 5 seconds, then scroll down 1 tick. 
![image](https://user-images.githubusercontent.com/46079004/166675525-d1419663-b0b1-4869-8261-822bdb73a53c.png)

**Comment by sy-records** [comment] 2022-05-11 06:43
I can't reproduce your problem in Chrome

**Comment by Zaeems** [comment] 2022-05-11 11:11
> I can't reproduce your problem in Chrome

I also cannot recreate it on Chrome.
On the other hand, I can recreate it on Edge.

https://user-images.githubusercontent.com/46079004/167836198-702fee61-8a41-40eb-8fed-25b4e178bbfc.mp4

**Comment by jhildenbiddle** [comment] 2024-07-19 16:22
This issue has been (likely) addressed by PR #2469. The changes will be available when Docsify v5 is released.

**Closed** 2024-07-19 16:45 UTC
Labels: needs investigation
