### ISSUE TITLE
Search Plugin Not Working

### ISSUE THREAD

**Issue by Ares-X** [docsifyjs/docsify#1400] opened 2020-10-15 15:36 UTC
#### Steps to reproduce

fist time open docsify website , search plugin is working correct , after click some page , search-min.js throw error ，and  search plugin not working any more , type something to search won't get any thing response

#### What is current behaviour

when open some page

```
search.min.js:1 Uncaught TypeError: Cannot read property '/./IOT%E5%AE%89%E5%85%A8/360/360%20Phone%20N6%20Pro%E5%86%85%E6%A0%B8%E6%BC%8F%E6%B4%9E' of null
    at search.min.js:1
    at Array.forEach (<anonymous>)
    at i (search.min.js:1)
    at search.min.js:1
    at o (docsify.min.js:1)
    at o (docsify.min.js:1)
    at B (docsify.min.js:1)
    at r (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
```
![image](https://user-images.githubusercontent.com/30471149/96152450-24d18800-0f3f-11eb-82b6-c06ef29a1379.png)

type something to search 

```
search.min.js:1 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at c (search.min.js:1)
    at r (search.min.js:1)
    at search.min.js:1
```
![image](https://user-images.githubusercontent.com/30471149/96152386-14211200-0f3f-11eb-81cf-e1ecd9b7da5f.png)

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: 
- Node.js version: 
- npm/yarn version: 
- Browser version: 
- Docsify version:  newest
- Docsify plugins:  search

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by Koooooo-7** [comment] 2020-10-15 15:46
Could u make it in Sandbox or ur site where it can be reproduced?
Due to the console err, it seems not clearly.

**Comment by Ares-X** [comment] 2020-10-15 16:14
here is my website https://ares-x.com/wiki/ password: qaxniubi
open some page and wait a while , search will not working 
![image](https://user-images.githubusercontent.com/30471149/96157063-69abed80-0f44-11eb-80e5-103151ed1f99.png)

**Comment by sy-records** [comment] 2020-10-16 00:24
Modify the search plugin to `search.js`. Don't use `min` so we can check for errors!

Change the path to English and try again. https://ares-x.com/wiki/_sidebar.md

Refer to docsify's sidebar document. https://docsify.js.org/_sidebar.md

**Comment by Koooooo-7** [comment] 2020-10-16 01:51
According to the console information, I doubt that your files of ur site r too much to be stored in the `LocalStorage` as `search.index`. 😅 
Could you remove the most of contents and hv a test again.  Waiting for ur feedback.

**Comment by Ares-X** [comment] 2020-10-16 03:52
> According to the console information, I doubt that your files of ur site r too much to be stored in the `LocalStorage` as `search.index`. 😅
> Could you remove the most of contents and hv a test again. Waiting for ur feedback.

maybe that's true , this problem doesn't happened on my mac , seem like only effect windows or mobile device?

**Comment by Ares-X** [comment] 2020-10-16 05:21
i delete a lot of contents , then work fine on windows device , so is there any way to solve this problem?

**Comment by sy-records** [comment] 2020-10-16 06:48
see https://github.com/docsifyjs/docsify/issues/1400#issuecomment-709657743

**Comment by Ares-X** [comment] 2020-10-16 07:24
> see [#1400 (comment)](https://github.com/docsifyjs/docsify/issues/1400#issuecomment-709657743)
> 
> You can convert the path to English to reduce the occupation.

![image](https://user-images.githubusercontent.com/30471149/96224707-96064f00-0fc2-11eb-9878-efca4115cee2.png)
i don't think is chinese path cause this error, i have tried many time on local server ,it doesn't have any problem
 i already changed `search-min.js` to `search.js` it seems like working correct now

**Comment by sy-records** [comment] 2020-10-16 07:27
I'm just suggesting, otherwise your url would be long.

**Comment by Ares-X** [comment] 2020-10-16 07:32
thanks for help

**Comment by Koooooo-7** [comment] 2020-10-16 14:02
Is the issue still exsit?
I guess we need investigation more about it. Could u reset ur site to make the exception reproduciable? thx in advance. 
IIRC,the localstorage size is relatived to the browser, I m not sure what makes the difference on different OS. r they the same browsers which u used on Win and Mac?
AFAIK, We havent a solution about it yet, actully, I guess we havnt thought about such a big content in docsify. 🤫

**Comment by Ares-X** [comment] 2020-10-16 14:12
> Is the issue still exsit?
> I guess we need investigation more about it. Could u reset ur site to make the exception reproduciable? thx in advance.
> IIRC,the localstorage size is relatived to the browser, I m not sure what makes the difference on different OS. r they the same browsers which u used on Win and Mac?
> AFAIK, We havent a solution about it yet, actully, I guess we havnt thought about such a big content in docsify. 🤫

after i changed search-min.js to search.js this problem seem doesn't exist

i used chrome on my mac and win , macos works fine ,but windows has this problem, and i also told my friend to try it ,use firefox and chrome on his windows device , he also have this problem

here is the old version to reproduce this bug
https://ares-x-github-io-41iddeg6s.vercel.app/wiki/  pass:`qaxniubi`
use chrome on windows open it , at the first time search won't have problem, click some page and wait a monment , open f12 console and try to search anything ,you will see those error i post before

![image](https://user-images.githubusercontent.com/30471149/96269100-80ae1680-0ffc-11eb-9145-af92848a6e3a.png)

**Comment by Koooooo-7** [comment] 2020-10-16 14:33
>after i changed search-min.js to search.js this problem seem doesn't exist  

It seems weird. 😅 

thx again,  we will check it and make sure what happened actually.

cc @anikethsaha PTAL,  I think there should have something needs be digged out.

**Comment by Ares-X** [comment] 2020-10-16 14:36
by the way , ios device still have this problem after changed to search.js 
try here https://ares-x.com/wiki/
device: iphone 6s plus 
ios version: 13.7

**Comment by anikethsaha** [comment] 2020-10-16 14:47
> > after i changed search-min.js to search.js this problem seem doesn't exist
> 
> It seems weird. 😅
> 
> thx again, we will check it and make sure what happened actually.
> 
> cc @anikethsaha PTAL, I think there should have something needs be digged out.

yea....we need to have a look in it.

**Comment by Koooooo-7** [comment] 2020-10-16 14:58
FYI. I increased the localstorage size 10 times larger and got the `search.index`  size ( `5411729` bytes, more than 5M).
![image](https://user-images.githubusercontent.com/33706142/96273899-7727ad00-1002-11eb-863a-ac7d4f156f2f.png)

**Comment by anikethsaha** [comment] 2020-10-16 15:47
weird, from which version this is happening ?

**Comment by Koooooo-7** [comment] 2020-10-16 16:01
> weird, from which version this is happening ?

IMHO, I think the problem since we set the `search.index` in local storage.
As we all know, the browsers have default local storage size  (about 5 M), and we stored all the markdown files strings  as `search.index` in local storage.
If the files strings r humongous (more than 5 M), we can't set it in the local storage and cause the search err aboved.

**Comment by Ares-X** [comment] 2020-10-18 06:54
> > weird, from which version this is happening ?
> 
> IMHO, I think the problem since we set the `search.index` in local storage.
> As we all know, the browsers have default local storage size (about 5 M), and we stored all the markdown files strings as `search.index` in local storage.
> If the files strings r humongous (more than 5 M), we can't set it in the local storage and cause the search err aboved.

https://github.com/wzpan/hexo-generator-search 

Maybe you can refer to this save all markdown file strings to a local xml file

**Comment by Anilople** [comment] 2020-11-19 11:12
```javascript
    window.$docsify = {
      loadSidebar: true,
      ....
    }
```
when `loadSidebar` is `true`, the search work again, and just the content was indexed in side bar's reference.

If the content not in side bar‘s reference, they can't be searched.

So strange.

In my project, record it. https://anilople.github.io/find-spirit/#/

**Comment by sy-records** [comment] 2020-11-19 11:33
@Anilople You mean you can't search there?

![image](https://user-images.githubusercontent.com/33931153/99660884-f98e0b80-2a9d-11eb-916d-4d652e02b996.png)

This one? If so, then it's fixed.

**Comment by Anilople** [comment] 2020-11-19 12:09
@sy-records 

Yes.

Let me give more example.

### content can't be search

![find](https://user-images.githubusercontent.com/15523186/99664384-124cf000-2aa3-11eb-981a-0d56ef21c98d.png)

![移动](https://user-images.githubusercontent.com/15523186/99664425-1c6eee80-2aa3-11eb-9cd7-8db1683b6466.png)


### content can be search

![ele](https://user-images.githubusercontent.com/15523186/99664237-d580f900-2aa2-11eb-9b8e-2df238923eff.png)

![world](https://user-images.githubusercontent.com/15523186/99664329-fd705c80-2aa2-11eb-8b17-8a346557e6ed.png)

**Comment by sy-records** [comment] 2020-11-19 14:50
fixed via #1391

**Comment by Anilople** [comment] 2020-11-19 14:59
> fixed via #1391

My docsify version is `4.11.6`

Found that there is no code describe like #1391 
in my [docsify/lib/plugins/search.js](https://github.com/Anilople/find-spirit/blob/891149a856b110233114fc02a9d5f5dfb893dd7c/docs/vendor/docsify/lib/plugins/search.js#L252) file. So the problem occur.

**Comment by sy-records** [comment] 2020-11-19 15:01
Yes, the official version has not been released yet. You can try to build it yourself.

**Comment by Mengsanit168** [comment] 2020-12-14 22:02
mengsanit168@gmail.com

**Comment by CircArgs** [comment] 2023-11-14 04:15
@sy-records I noticed you cited a fix, and this issue is still open. I am getting a set of errors that appear extremely similar to those of this issue:
```sh
docsify.min.js:1 Docsify plugin error TypeError: Cannot read properties of null (reading '/')
    at VM6904 search.js:347:17

 ... lots more 

VM6904 search.js:208 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at search (VM6904 search.js:208:12)
    at doSearch (VM6904 search.js:402:18)
    at VM6904 search.js:440:49
```

Loading in the bare `search.js` and poking around, the error stems from these lines:

```js
    Object.keys(INDEXS).forEach(function (key) {
      data = data.concat(Object.keys(INDEXS[key]).map(function (page) { return INDEXS[key][page]; }));
    });
```

I've tried multiple `paths` configurations and inspected many of the awesome-docsify sites and can't spot any real differences with my setup here: https://github.com/CircArgs/cppfront

Any help would be greatly appreciated! Thank you

**Comment by sy-records** [comment] 2023-11-14 06:05
@CircArgs I didn't reproduce your question. If you're using GitHub Pages, you should try setting `basePath: 'cppfront'`

<img width="528" alt="image" src="https://github.com/docsifyjs/docsify/assets/33931153/4d538a02-548e-462a-9ab9-0768001df6f2">

---

If you still have problems you can resubmit a new issue instead of replying here and I will close this.

**Closed by sy-records** 2023-11-14 06:05 UTC
Labels: enhancement, needs investigation, needs discussion

**Comment by CircArgs** [comment] 2023-11-14 14:12
@sy-records Thanks for trying! I was testing on Brave. It seems it was a permission issue. Worked on Chrome. Thanks again.
