### ISSUE TITLE
cssEscape is not defined

### ISSUE THREAD

**Issue by scastagnoli** [docsifyjs/docsify#1058] opened 2020-03-09 12:25 UTC
## Bug Report
From cosle browser I see: "ReferenceError: cssEscape is not defined"

#### Steps to reproduce
docsify serve ./docs2
Browser url = http:/localhost:3000

#### What is current behaviour
Browser tells "cssEscape is not defined" on browser console
Browser page says: "Loading..."

#### What is the expected behaviour
I cannot see standard page. I have the three file generated with command docsify init ./docs2:
.nojekyll
index.html
README.md

#### Other relevant information

- [ ] Bug does still occur when all/other plugins are disabled?

- Your OS: Windows 10
- Node.js version: 10.15.1
- npm/yarn version: 4.1.1
- Browser version: Firefox 73.0.1
- Docsify version: just installed from npm
- Docsify plugins: none

**Comment by xuqingkuang** [comment] 2020-03-09 12:25
Same issue here. - http://hippyjs.org/

**Comment by raulfdm** [comment] 2020-03-09 12:26
same issue here https://raulmelo-notebook.netlify.com/

**Comment by anikethsaha** [comment] 2020-03-09 12:27
Please use `4.10.2` for a while till new version is coming !

**Comment by raulfdm** [comment] 2020-03-09 12:31
> Please use `4.10.2` for a while till new version is coming !

workaround:

```html
<script src="//unpkg.com/docsify@4.10.2/lib/docsify.js"></script>
```

**Comment by xuqingkuang** [comment] 2020-03-09 12:35
It seems the issue is fixing in 5f86454, and I chose to wait for the new version to be published.

**Comment by LogicJake** [comment] 2020-03-09 12:45
Scared me

**Comment by anikethsaha** [comment] 2020-03-09 12:53
release `v4.11.1`
Please confirm if there is any issues or not

**Comment by Floppy** [comment] 2020-03-09 13:02
Fixed here using the default unpkg URLs.

**Comment by anikethsaha** [comment] 2020-03-09 13:03
Closing as its been fix.
Please open new issue if any other issue is there

**Closed** 2020-03-09 13:04 UTC
