### ISSUE TITLE
Search Page Turn Failed

### ISSUE THREAD

**Issue by why1213888888** [docsifyjs/docsify#1622] opened 2021-08-13 08:28 UTC
## Bug Report
Click search results ，page forward fail
Enter the address to access the website ，page forward fail.

#### Steps to reproduce
Click search results ，page forward fail，reflash page will success.

#### What is current behaviour
![4c80a11edc9784af85489388d801c92](https://user-images.githubusercontent.com/71311757/129328004-8f5e994a-8e32-47d6-8c44-a2b8fad46b1c.png)
![19da8709ceef84cd19bce90fecd07ba](https://user-images.githubusercontent.com/71311757/129328020-b0061c7e-cf20-4fcb-9725-55f86e01dd80.png)

#### What is the expected behaviour
![f7d95c86c916d66223058a4f765dad7](https://user-images.githubusercontent.com/71311757/129328037-d2ad6622-09e9-4e5a-82ac-d2861e58d91e.png)

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Your OS: win10
- Node.js version: 14.17.0
- npm/yarn version: 6.14.13
- Browser version: 
- Docsify version: 
- Docsify plugins: 

#### Please create a reproducible sandbox 

[![Edit 307qqv236](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307qqv236)

**Comment by sy-records** [comment] 2021-08-13 08:42
What does `page forward fail` mean?

**Comment by why1213888888** [comment] 2021-08-13 09:17
> What does `page forward fail` mean?

点击个别搜索结果跳转，不能定位到正确的位置

**Comment by sy-records** [comment] 2021-08-13 09:19
复现问题的仓库地址和访问地址发下

**Comment by why1213888888** [comment] 2021-08-13 09:32
> 复现问题的仓库地址和访问地址发下

https://opentools.95516.com/applet/#/

**Comment by sy-records** [comment] 2021-08-16 05:47
I couldn't reproduce the problem, so I closed it first.
----

issue先关掉了。测试都能跳转，但是你这里的搜索结果好像是有点问题，应该是在一起的，你这里两结果分开了。

但是你使用的不是官方地址的js，提供下文档仓库地址吧。

![image](https://user-images.githubusercontent.com/33931153/129516430-d91721ef-9262-46bf-b693-9412c72f0811.png)

**Closed by sy-records** 2021-08-16 05:47 UTC
