### ISSUE TITLE
Docsify can not render an embedded 

### ISSUE THREAD

**Issue by fgaule** [docsifyjs/docsify#1499] opened 2021-02-08 15:14 UTC
#### Steps to reproduce
1. Import tab plugin
2. Create a .md file with a tab
3. Import that .md into any other .m using the embedded feature

#### What is current behaviour
When you embedded a .md it is not being rendered.

#### What is the expected behaviour
When you embedded a .md should be rendered. In this case, tabs should be displayed as when they are inline.

#### Other relevant information

- [ X] Bug does still occur when all/other plugins are disabled?

- Your OS: iOS 10.15.7 (19H2)
- Node.js version: v14.6.0
- npm/yarn version:  npm 6.14.7
- Browser version: Chrome Version 88.0.4324.146 (Official Build) (x86_64)
- Docsify version: docsify@4
- Docsify plugins:  docsify-tabs@1

Related [issue](https://github.com/jhildenbiddle/docsify-tabs/issues/31)

#### Please create a reproducible sandbox 

https://github.com/fgaule/docsfy-embedded-not-rendering/tree/main/docs

**Comment by jhildenbiddle** [comment] 2021-02-08 23:51
From the [linked issue](https://github.com/jhildenbiddle/docsify-tabs/issues/31) originally filed in the [docsify-tabs](https://github.com/jhildenbiddle/docsify-tabs) repo:

> Unfortunately, this is a limitation of docsify's plugin system and not something that docsify-tabs can easily resolve. The short explanation is that docsify's plugin system functions at the page level, so there is no "hook" to leverage for processing content that is loaded via an embed.

Today we have `beforeEach`, `afterEach`, and `doneEach` plugin hooks, all of which operate on the page-level:

```js
function(hook, vm) {
  hook.beforeEach(function(content, next) {
    // Invoked each time before parsing the Markdown file.
    // ...
    return content;
  });

  hook.afterEach(function(html, next) {
    // Invoked each time after the Markdown file is parsed.
    // ...
    return html;
  });

  hook.doneEach(function() {
    // Invoked each time after the data is fully loaded, no arguments,
    // ...
  });
}
```

Offering markdown-specific plugin hooks (e.g. `beforeMarkdown` and `afterMarkdown`) would give docsify the ability to create a separate, under-the-hood markdown-specific plugin pipeline that could be applied to all markdown content:

```js
function(hook, vm) {
  hook.beforeEach(function() {
    // Invoked before loading new page content
    // Useful for cleanup/teardown
    // ...
  });

  hook.beforeMarkdown(function(md, next) {
    // Invoked before parsing Markdown
    // ...
    return md;
  });

  hook.afterMarkdown(function(html, next) {
    // Invoked after parsing Markdown
    // ...
    return html;
  });

  hook.doneEach(function() {
    // Invoked each time after the data is fully loaded, no arguments,
    // ...
  });
}
```

**Comment by ayjw** [comment] 2021-09-22 08:31
I also encounter this problem, want to know how to solve

**Comment by Hyddan** [comment] 2023-10-12 09:49
We also ran into this issue with docsify-tabs and wrote our own plugin for tabs: [useless-docsify-tabs](https://github.com/useless-media/useless-docsify-tabs). It doesn't have as many features as docsify-tabs but it does work when embedded.

**Comment by jhildenbiddle** [comment] 2024-03-02 04:08
Marking as duplicate of more appropriately named issue: #2373

**Closed by jhildenbiddle** 2024-03-02 04:08 UTC
Labels: enhancement
