### ISSUE TITLE
[BUG] executes scripts twice

### ISSUE THREAD

**Issue by trusktr** [docsifyjs/docsify#906] opened 2019-08-17 23:32 UTC
## Bug Report

If `executeScript` is `true`, then Docsify executes the content of the `<script>` twice. This causes bugs. Users don't expect a script tag to run twice.

#### Steps to reproduce

Just look here:

https://github.com/docsifyjs/docsify/blob/develop/src/core/render/index.js#L51-L64

That conditional statement will execute the content of the script by calling `executeScript`, and the browser will _**also**_ naturally execute the script when the `<script>` is inserted into the DOM.

#### What is current behaviour

It executes the script twice!

#### What is the expected behaviour

Scripts should be executed only once.

#### Other relevant information

- [x] Bug does still occur when all/other plugins are disabled?

- Docsify version: 4.9.4

**Comment by anikethsaha** [comment] 2019-11-22 20:24
> **What is current behavior**
> 
> It executes the script twice!

Did you face the execution of the script twice ? or its because of the code ? i

I think this might help, _(though not 100% sure )_

`executeScript` to `true` mean that running script tag coming from markdown. this are not the one which you are writing in the HTML's header tag or which you are writing to HTML page by yourself.
So as they are coming from markdown as a string and markdown are not parsing it, its skipping the rendering phase. So we need to manually run those code. So you can see [`here`](https://github.com/docsifyjs/docsify/blob/develop/src/core/render/index.js#L26-L28) it's running the inner js code. Its like if you want to execute some javascript code in the HTML , then you can write it in the markdown and then it will be executed. Its not executing script tags outside of the markdown.

You can see the example here 

[`Markdown-script-code`](https://github.com/docsifyjs/docsify/blob/develop/docs/themes.md#click-to-preview)

[Preview-of how it executed](https://docsify.js.org/#/themes?id=click-to-preview)

![image](https://user-images.githubusercontent.com/26347874/69457842-f9c4cf80-0d93-11ea-9d2a-d4acf2e0511e.png)


I hope this helps.
Closing this. Please comment if its unclear or anything is wrong with it 👍

**Comment by trusktr** [comment] 2022-01-23 05:15
Sorry for the late reply, but Docsify is in fact running the script from the markdown (not the HTML template) twice. I need to investigate this, and will open this as a reminder.

**Comment by trusktr** [comment] 2022-01-23 07:00
https://github.com/docsifyjs/docsify/issues/1732 might possibly lead to clues.

**Comment by jhildenbiddle** [comment] 2022-03-12 05:23
Not seeing this behavior on 4.12.1. or 4.12.2. Closing for now, but feel free to reopen if the issue is reproducible.

**Closed by jhildenbiddle** 2022-03-12 05:23 UTC
Labels: bug
