### ISSUE TITLE
do not access to https://cdn.jsdelivr.net/npm/docsify@4 

### ISSUE THREAD

**Issue by caorenpeng-kaer** [docsifyjs/docsify#1801] opened 2022-05-17 10:19 UTC
we cant access to https://cdn.jsdelivr.net/npm/docsify@4 ,The page cannot be rendered。

**Comment by sy-records** [comment] 2022-05-17 10:54
Duplicate of https://github.com/docsifyjs/docsify/issues/1795

**Closed by sy-records** 2022-05-17 10:54 UTC
